# Generated by Django 4.1.2 on 2023-01-04 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_item_encrypted_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='encrypted_data',
        ),
    ]
