# Generated by Django 4.1.2 on 2023-04-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_epf_options_alter_otherliability_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_value',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='epf',
            name='account_value',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='sum_insured',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='account_value',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
    ]
