# Generated by Django 4.1.2 on 2023-01-04 05:18

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_vehicle_socso_property_otherasset_investment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='encrypted_data',
            field=django_cryptography.fields.encrypt(models.JSONField(blank=True, null=True)),
        ),
    ]
