# Generated by Django 4.1.2 on 2023-01-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_insurance_insurance_type_alter_insurance_policy_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='property',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='account_value',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='account_value',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='postcode',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='residential_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='titleno',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='make_model',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_no',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
